export const categories = [
  { id: 1, category: "Fiction" },
  { id: 2, category: "Non-Fiction" },
  { id: 3, category: "Sci-Fi" },
  { id: 4, category: "Fantasy" },
  { id: 5, category: "Mystery" },
  { id: 6, category: "Romance" },
  { id: 7, category: "Biography" },
];

export const booksByCategory = {
  Fiction: [
    {
      id: "f1",
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      category: "Fiction",
      rating: 4.6,
      publishedYear: 1960,
      pages: 336,
      language: "English",
      description: "A novel about racial injustice and moral growth.",
      image: "/images/f1.jpg",
      isPopular: true,
    },
    {
      id: "f2",
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      category: "Fiction",
      rating: 4.5,
      publishedYear: 1925,
      pages: 180,
      language: "English",
      description: "A critique of the American Dream.",
      image: "/images/f2.jpg",
      isPopular: true,
    },
    {
      id: "f3",
      title: "Pride and Prejudice",
      author: "Jane Austen",
      category: "Fiction",
      rating: 4.7,
      publishedYear: 1813,
      pages: 279,
      language: "English",
      description: "A romantic classic.",
      image: "/images/f3.jpg",
      isPopular: false,
    },
    {
      id: "f4",
      title: "1984",
      author: "George Orwell",
      category: "Fiction",
      rating: 4.6,
      publishedYear: 1949,
      pages: 328,
      language: "English",
      description: "A dystopian novel on surveillance.",
      image: "/images/f4.jpg",
      isPopular: true,
    },
    {
      id: "f5",
      title: "The Kite Runner",
      author: "Khaled Hosseini",
      category: "Fiction",
      rating: 4.6,
      publishedYear: 2003,
      pages: 371,
      language: "English",
      description: "A story of friendship and redemption.",
      image: "/images/f5.jpg",
      isPopular: true,
    },
    {
      id: "f6",
      title: "Life of Pi",
      author: "Yann Martel",
      category: "Fiction",
      rating: 4.4,
      publishedYear: 2001,
      pages: 331,
      language: "English",
      description: "A survival tale with philosophy.",
      image: "/images/f6.jpg",
      isPopular: false,
    },
    {
      id: "f7",
      title: "Little Women",
      author: "Louisa May Alcott",
      category: "Fiction",
      rating: 4.5,
      publishedYear: 1868,
      pages: 449,
      language: "English",
      description: "A coming-of-age family novel.",
      image: "/images/f7.jpg",
      isPopular: false,
    },
    {
      id: "f8",
      title: "The Book Thief",
      author: "Markus Zusak",
      category: "Fiction",
      rating: 4.7,
      publishedYear: 2005,
      pages: 552,
      language: "English",
      description: "A WWII story narrated by Death.",
      image: "/images/f8.jpg",
      isPopular: true,
    },
    {
      id: "f9",
      title: "Jane Eyre",
      author: "Charlotte Brontë",
      category: "Fiction",
      rating: 4.6,
      publishedYear: 1847,
      pages: 500,
      language: "English",
      description: "A strong woman’s journey.",
      image: "/images/f9.jpg",
      isPopular: false,
    },
    {
      id: "f10",
      title: "The Road",
      author: "Cormac McCarthy",
      category: "Fiction",
      rating: 4.3,
      publishedYear: 2006,
      pages: 287,
      language: "English",
      description: "A post-apocalyptic survival story.",
      image: "/images/f10.jpg",
      isPopular: false,
    },
  ],

  "Non-Fiction": [
    {
      id: "nf1",
      title: "Atomic Habits",
      author: "James Clear",
      category: "Non-Fiction",
      rating: 4.8,
      publishedYear: 2018,
      pages: 320,
      language: "English",
      description: "Build good habits and break bad ones.",
      image: "/images/nf1.jpg",
      isPopular: true,
    },
    {
      id: "nf2",
      title: "Sapiens",
      author: "Yuval Noah Harari",
      category: "Non-Fiction",
      rating: 4.7,
      publishedYear: 2011,
      pages: 498,
      language: "English",
      description: "A brief history of humankind.",
      image: "/images/nf2.jpg",
      isPopular: true,
    },
    {
      id: "nf3",
      title: "Educated",
      author: "Tara Westover",
      category: "Non-Fiction",
      rating: 4.7,
      publishedYear: 2018,
      pages: 352,
      language: "English",
      description: "A memoir of self-education.",
      image: "/images/nf3.jpg",
      isPopular: false,
    },
    {
      id: "nf4",
      title: "Becoming",
      author: "Michelle Obama",
      category: "Non-Fiction",
      rating: 4.8,
      publishedYear: 2018,
      pages: 448,
      language: "English",
      description: "The former First Lady’s memoir.",
      image: "/images/nf4.jpg",
      isPopular: true,
    },
    {
      id: "nf5",
      title: "Deep Work",
      author: "Cal Newport",
      category: "Non-Fiction",
      rating: 4.6,
      publishedYear: 2016,
      pages: 304,
      language: "English",
      description: "Rules for focused success.",
      image: "/images/nf5.jpg",
      isPopular: false,
    },
    {
      id: "nf6",
      title: "The Power of Habit",
      author: "Charles Duhigg",
      category: "Non-Fiction",
      rating: 4.5,
      publishedYear: 2012,
      pages: 371,
      language: "English",
      description: "The science of habits.",
      image: "/images/nf6.jpg",
      isPopular: false,
    },
    {
      id: "nf7",
      title: "Ikigai",
      author: "Héctor García",
      category: "Non-Fiction",
      rating: 4.3,
      publishedYear: 2016,
      pages: 208,
      language: "English",
      description: "The Japanese secret to happiness.",
      image: "/images/nf7.jpg",
      isPopular: false,
    },
    {
      id: "nf8",
      title: "Outliers",
      author: "Malcolm Gladwell",
      category: "Non-Fiction",
      rating: 4.5,
      publishedYear: 2008,
      pages: 336,
      language: "English",
      description: "The story of success.",
      image: "/images/nf8.jpg",
      isPopular: false,
    },
    {
      id: "nf9",
      title: "Grit",
      author: "Angela Duckworth",
      category: "Non-Fiction",
      rating: 4.6,
      publishedYear: 2016,
      pages: 352,
      language: "English",
      description: "Passion and perseverance.",
      image: "/images/nf9.jpg",
      isPopular: false,
    },
    {
      id: "nf10",
      title: "Can't Hurt Me",
      author: "David Goggins",
      category: "Non-Fiction",
      rating: 4.7,
      publishedYear: 2018,
      pages: 364,
      language: "English",
      description: "Mental toughness and discipline.",
      image: "/images/nf10.jpg",
      isPopular: true,
    },
  ],
  "Sci-Fi": [
    {
      id: "sf1",
      title: "Dune",
      author: "Frank Herbert",
      category: "Sci-Fi",
      rating: 4.6,
      publishedYear: 1965,
      pages: 412,
      language: "English",
      description: "An epic science fiction novel set on Arrakis.",
      image: "/images/sf1.jpg",
      isPopular: true,
    },
    {
      id: "sf2",
      title: "Foundation",
      author: "Isaac Asimov",
      category: "Sci-Fi",
      rating: 4.6,
      publishedYear: 1951,
      pages: 255,
      language: "English",
      description: "A saga of the fall and rise of civilizations.",
      image: "/images/sf2.jpg",
      isPopular: false,
    },
    {
      id: "sf3",
      title: "Ender's Game",
      author: "Orson Scott Card",
      category: "Sci-Fi",
      rating: 4.7,
      publishedYear: 1985,
      pages: 324,
      language: "English",
      description: "A young boy trained to save humanity.",
      image: "/images/sf3.jpg",
      isPopular: true,
    },
    {
      id: "sf4",
      title: "The Martian",
      author: "Andy Weir",
      category: "Sci-Fi",
      rating: 4.7,
      publishedYear: 2011,
      pages: 387,
      language: "English",
      description: "A stranded astronaut fights to survive on Mars.",
      image: "/images/sf4.jpg",
      isPopular: true,
    },
    {
      id: "sf5",
      title: "Neuromancer",
      author: "William Gibson",
      category: "Sci-Fi",
      rating: 4.4,
      publishedYear: 1984,
      pages: 271,
      language: "English",
      description: "A cyberpunk classic.",
      image: "/images/sf5L.jpg",
      isPopular: false,
    },
    {
      id: "sf6",
      title: "Snow Crash",
      author: "Neal Stephenson",
      category: "Sci-Fi",
      rating: 4.5,
      publishedYear: 1992,
      pages: 470,
      language: "English",
      description: "A fast-paced cyberpunk adventure.",
      image: "/images/sf6.jpg",
      isPopular: false,
    },
    {
      id: "sf7",
      title: "Brave New World",
      author: "Aldous Huxley",
      category: "Sci-Fi",
      rating: 4.5,
      publishedYear: 1932,
      pages: 288,
      language: "English",
      description: "A dystopian future controlled by technology.",
      image: "/images/sf7.jpg",
      isPopular: true,
    },
    {
      id: "sf8",
      title: "The Time Machine",
      author: "H.G. Wells",
      category: "Sci-Fi",
      rating: 4.3,
      publishedYear: 1895,
      pages: 118,
      language: "English",
      description: "A journey through time.",
      image: "/images/sf8.jpg",
      isPopular: false,
    },
    {
      id: "sf9",
      title: "Red Mars",
      author: "Kim Stanley Robinson",
      category: "Sci-Fi",
      rating: 4.5,
      publishedYear: 1992,
      pages: 572,
      language: "English",
      description: "The colonization of Mars.",
      image: "/images/sf9.jpg",
      isPopular: false,
    },
    {
      id: "sf10",
      title: "Do Androids Dream of Electric Sheep?",
      author: "Philip K. Dick",
      category: "Sci-Fi",
      rating: 4.4,
      publishedYear: 1968,
      pages: 210,
      language: "English",
      description: "A world where androids blur humanity.",
      image: "/images/sf10.jpg",
      isPopular: false,
    },
  ],

  Fantasy: [
    {
      id: "fa1",
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      category: "Fantasy",
      rating: 4.8,
      publishedYear: 1937,
      pages: 310,
      language: "English",
      description: "A fantasy adventure before LOTR.",
      image: "/images/fa1.jpg",
      isPopular: true,
    },
    {
      id: "fa2",
      title: "The Name of the Wind",
      author: "Patrick Rothfuss",
      category: "Fantasy",
      rating: 4.8,
      publishedYear: 2007,
      pages: 662,
      language: "English",
      description: "The story of a gifted young magician.",
      image: "/images/fa2.jpg",
      isPopular: true,
    },
    {
      id: "fa3",
      title: "Mistborn",
      author: "Brandon Sanderson",
      category: "Fantasy",
      rating: 4.7,
      publishedYear: 2006,
      pages: 541,
      language: "English",
      description: "A unique magic system and rebellion.",
      image: "/images/fa3.jpg",
      isPopular: true,
    },
    {
      id: "fa4",
      title: "The Way of Kings",
      author: "Brandon Sanderson",
      category: "Fantasy",
      rating: 4.8,
      publishedYear: 2010,
      pages: 1007,
      language: "English",
      description: "An epic high-fantasy masterpiece.",
      image: "/images/fa4.jpg",
      isPopular: false,
    },
    {
      id: "fa5",
      title: "Eragon",
      author: "Christopher Paolini",
      category: "Fantasy",
      rating: 4.5,
      publishedYear: 2002,
      pages: 544,
      language: "English",
      description: "A young dragon rider’s journey.",
      image: "/images/fa5.jpg",
      isPopular: false,
    },
    {
      id: "fa6",
      title: "American Gods",
      author: "Neil Gaiman",
      category: "Fantasy",
      rating: 4.4,
      publishedYear: 2001,
      pages: 465,
      language: "English",
      description: "Old gods versus new gods.",
      image: "/images/fa6.jpg",
      isPopular: false,
    },
    {
      id: "fa7",
      title: "Percy Jackson",
      author: "Rick Riordan",
      category: "Fantasy",
      rating: 4.7,
      publishedYear: 2005,
      pages: 377,
      language: "English",
      description: "Greek mythology in the modern world.",
      image: "/images/fa7.jpg",
      isPopular: true,
    },
    {
      id: "fa8",
      title: "The Witcher",
      author: "Andrzej Sapkowski",
      category: "Fantasy",
      rating: 4.6,
      publishedYear: 1993,
      pages: 384,
      language: "English",
      description: "A monster hunter in a dark fantasy world.",
      image: "/images/fa8.jpg",
      isPopular: false,
    },
    {
      id: "fa9",
      title: "The Dark Tower",
      author: "Stephen King",
      category: "Fantasy",
      rating: 4.5,
      publishedYear: 1982,
      pages: 224,
      language: "English",
      description: "A blend of fantasy, horror, and sci-fi.",
      image: "/images/fa9.jpg",
      isPopular: false,
    },
    {
      id: "fa10",
      title: "The Magicians",
      author: "Lev Grossman",
      category: "Fantasy",
      rating: 4.3,
      publishedYear: 2009,
      pages: 402,
      language: "English",
      description: "Dark fantasy at a magical university.",
      image: "/images/fa10.jpg",
      isPopular: false,
    },
  ],

  Mystery: [
    {
      id: "m1",
      title: "And Then There Were None",
      author: "Agatha Christie",
      category: "Mystery",
      rating: 4.8,
      publishedYear: 1939,
      pages: 264,
      language: "English",
      description: "Ten strangers trapped on an island.",
      image: "/images/m1.jpg",
      isPopular: true,
    },
    {
      id: "m2",
      title: "Gone Girl",
      author: "Gillian Flynn",
      category: "Mystery",
      rating: 4.3,
      publishedYear: 2012,
      pages: 432,
      language: "English",
      description: "A twisted psychological thriller.",
      image: "/images/m2.jpg",
      isPopular: true,
    },
    {
      id: "m3",
      title: "The Da Vinci Code",
      author: "Dan Brown",
      category: "Mystery",
      rating: 4.3,
      publishedYear: 2003,
      pages: 454,
      language: "English",
      description: "A religious mystery thriller.",
      image: "/images/m3.jpg",
      isPopular: true,
    },
    {
      id: "m4",
      title: "The Silent Patient",
      author: "Alex Michaelides",
      category: "Mystery",
      rating: 4.6,
      publishedYear: 2019,
      pages: 336,
      language: "English",
      description: "A shocking psychological mystery.",
      image: "/images/m4.jpg",
      isPopular: true,
    },
    {
      id: "m5",
      title: "Big Little Lies",
      author: "Liane Moriarty",
      category: "Mystery",
      rating: 4.5,
      publishedYear: 2014,
      pages: 460,
      language: "English",
      description: "Secrets behind perfect lives.",
      image: "/images/m5.jpg",
      isPopular: false,
    },
    {
      id: "m6",
      title: "Rebecca",
      author: "Daphne du Maurier",
      category: "Mystery",
      rating: 4.6,
      publishedYear: 1938,
      pages: 449,
      language: "English",
      description: "A haunting gothic mystery.",
      image: "/images/m6.jpg",
      isPopular: false,
    },
    {
      id: "m7",
      title: "The Girl with the Dragon Tattoo",
      author: "Stieg Larsson",
      category: "Mystery",
      rating: 4.4,
      publishedYear: 2005,
      pages: 465,
      language: "English",
      description: "A dark Scandinavian thriller.",
      image: "/images/m7.jpg",
      isPopular: false,
    },
    {
      id: "m8",
      title: "In the Woods",
      author: "Tana French",
      category: "Mystery",
      rating: 4.4,
      publishedYear: 2007,
      pages: 429,
      language: "English",
      description: "A detective mystery novel.",
      image: "/images/m8.jpg",
      isPopular: false,
    },
    {
      id: "m9",
      title: "The Woman in White",
      author: "Wilkie Collins",
      category: "Mystery",
      rating: 4.5,
      publishedYear: 1859,
      pages: 672,
      language: "English",
      description: "A classic mystery thriller.",
      image: "/images/m9.jpg",
      isPopular: false,
    },
    {
      id: "m10",
      title: "Sharp Objects",
      author: "Gillian Flynn",
      category: "Mystery",
      rating: 4.3,
      publishedYear: 2006,
      pages: 254,
      language: "English",
      description: "A chilling psychological mystery.",
      image: "/images/m10.jpg",
      isPopular: false,
    },
  ],

  Romance: [
    {
      id: "r1",
      title: "Pride and Prejudice",
      author: "Jane Austen",
      category: "Romance",
      rating: 4.7,
      publishedYear: 1813,
      pages: 279,
      language: "English",
      description: "A timeless romantic classic.",
      image: "/images/r1.jpg",
      isPopular: true,
    },
    {
      id: "r2",
      title: "Me Before You",
      author: "Jojo Moyes",
      category: "Romance",
      rating: 4.6,
      publishedYear: 2012,
      pages: 369,
      language: "English",
      description: "A touching love story.",
      image: "/images/r2.jpg",
      isPopular: true,
    },
    {
      id: "r3",
      title: "The Notebook",
      author: "Nicholas Sparks",
      category: "Romance",
      rating: 4.6,
      publishedYear: 1996,
      pages: 214,
      language: "English",
      description: "A deeply emotional romance.",
      image: "/images/r3.jpg",
      isPopular: true,
    },
    {
      id: "r4",
      title: "Outlander",
      author: "Diana Gabaldon",
      category: "Romance",
      rating: 4.7,
      publishedYear: 1991,
      pages: 850,
      language: "English",
      description: "Romance through time.",
      image: "/images/r4.jpg",
      isPopular: false,
    },
    {
      id: "r5",
      title: "The Time Traveler's Wife",
      author: "Audrey Niffenegger",
      category: "Romance",
      rating: 4.5,
      publishedYear: 2003,
      pages: 546,
      language: "English",
      description: "A love story beyond time.",
      image: "/images/r5.jpg",
      isPopular: false,
    },
    {
      id: "r6",
      title: "Call Me By Your Name",
      author: "André Aciman",
      category: "Romance",
      rating: 4.4,
      publishedYear: 2007,
      pages: 256,
      language: "English",
      description: "A summer romance in Italy.",
      image: "/images/r6.jpg",
      isPopular: false,
    },
    {
      id: "r7",
      title: "It Ends With Us",
      author: "Colleen Hoover",
      category: "Romance",
      rating: 4.6,
      publishedYear: 2016,
      pages: 376,
      language: "English",
      description: "A modern emotional romance.",
      image: "/images/r7.jpg",
      isPopular: true,
    },
    {
      id: "r8",
      title: "Love & Other Words",
      author: "Christina Lauren",
      category: "Romance",
      rating: 4.5,
      publishedYear: 2018,
      pages: 432,
      language: "English",
      description: "A story of love and second chances.",
      image: "/images/nf1o0A2k0FEL.jpg",
      isPopular: false,
    },
    {
      id: "r9",
      title: "Twilight",
      author: "Stephenie Meyer",
      category: "Romance",
      rating: 4.3,
      publishedYear: 2005,
      pages: 498,
      language: "English",
      description: "A vampire romance.",
      image: "/images/r9.jpg",
      isPopular: false,
    },
    {
      id: "r10",
      title: "Anna Karenina",
      author: "Leo Tolstoy",
      category: "Romance",
      rating: 4.6,
      publishedYear: 1878,
      pages: 864,
      language: "English",
      description: "A tragic romantic novel.",
      image: "/images/r10.jpg",
      isPopular: false,
    },
  ],

  Biography: [
    {
      id: "b1",
      title: "The Diary of a Young Girl",
      author: "Anne Frank",
      category: "Biography",
      rating: 4.8,
      publishedYear: 1947,
      pages: 283,
      language: "English",
      description: "A young girl’s life during WWII.",
      image: "/images/b1.jpg",
      isPopular: true,
    },
    {
      id: "b2",
      title: "Long Walk to Freedom",
      author: "Nelson Mandela",
      category: "Biography",
      rating: 4.7,
      publishedYear: 1994,
      pages: 656,
      language: "English",
      description: "The autobiography of Nelson Mandela.",
      image: "/images/b2.jpg",
      isPopular: true,
    },
    {
      id: "b3",
      title: "Steve Jobs",
      author: "Walter Isaacson",
      category: "Biography",
      rating: 4.6,
      publishedYear: 2011,
      pages: 656,
      language: "English",
      description: "The life of Apple’s co-founder.",
      image: "/images/b3.jpg",
      isPopular: true,
    },
    {
      id: "b4",
      title: "Becoming",
      author: "Michelle Obama",
      category: "Biography",
      rating: 4.8,
      publishedYear: 2018,
      pages: 448,
      language: "English",
      description: "A deeply personal memoir.",
      image: "/images/b4.jpg",
      isPopular: true,
    },
    {
      id: "b5",
      title: "Wings of Fire",
      author: "A.P.J. Abdul Kalam",
      category: "Biography",
      rating: 4.7,
      publishedYear: 1999,
      pages: 180,
      language: "English",
      description: "The journey of an Indian scientist.",
      image: "/images/b5.jpg",
      isPopular: true,
    },
    {
      id: "b6",
      title: "I Am Malala",
      author: "Malala Yousafzai",
      category: "Biography",
      rating: 4.6,
      publishedYear: 2013,
      pages: 369,
      language: "English",
      description: "A story of courage and education.",
      image: "/images/b6.jpg",
      isPopular: false,
    },
    {
      id: "b7",
      title: "Elon Musk",
      author: "Ashlee Vance",
      category: "Biography",
      rating: 4.5,
      publishedYear: 2015,
      pages: 400,
      language: "English",
      description: "The life of a tech entrepreneur.",
      image: "/images/b7.jpg",
      isPopular: false,
    },
    {
      id: "b8",
      title: "The Story of My Experiments with Truth",
      author: "Mahatma Gandhi",
      category: "Biography",
      rating: 4.6,
      publishedYear: 1927,
      pages: 432,
      language: "English",
      description: "The autobiography of Mahatma Gandhi.",
      image: "/images/b8.jpg",
      isPopular: false,
    },
    {
      id: "b9",
      title: "Einstein: His Life and Universe",
      author: "Walter Isaacson",
      category: "Biography",
      rating: 4.6,
      publishedYear: 2007,
      pages: 675,
      language: "English",
      description: "The life of Albert Einstein.",
      image: "/images/b9.jpg",
      isPopular: false,
    },
    {
      id: "b10",
      title: "A Promised Land",
      author: "Barack Obama",
      category: "Biography",
      rating: 4.7,
      publishedYear: 2020,
      pages: 768,
      language: "English",
      description: "The memoir of Barack Obama.",
      image: "/images/b10.jpg",
      isPopular: false,
    },
  ],
};
